FROM phpmyadmin/phpmyadmin:latest
LABEL org.freenas.interactive="true" \
      org.freenas.expose-ports-at-host="true" \
      org.freenas.autostart="true" \
      org.freenas.port-mappings="8080:80/tcp" \
      org.freenas.upgradeable="false" 

