FROM streamcat/streamcat-rtmp:latest
LABEL org.freenas.interactive="true" \
      org.freenas.expose-ports-at-host="true" \
      org.freenas.autostart="true" \
      org.freenas.port-mappings="80:8080/tcp,1935:1935/tcp" \
      org.freenas.upgradeable="true" 

