FROM linagora/cyrus-imapd:latest
LABEL org.freenas.interactive="true" \
      org.freenas.expose-ports-at-host="true" \
      org.freenas.autostart="true" \
      org.freenas.dhcp="true" \
      org.freenas.upgradeable="true" 

